kind: "BuildConfig"
apiVersion: "build.openshift.io/v1"
metadata:
  name: "simple-pipeline"
spec:
  source:
    #contextDir: simple-pipeline
    git:
      uri: "https://github.com/anandpavithran/jenkins-demo1"
      #ref: "simple-pipeline"
  strategy:
    jenkinsPipelineStrategy:
      type: JenkinsPipeline
